[versions]
mod-version = "0.1.0"

# Fabric (https://fabricmc.net/develop)
minecraft = "1.21.10"
yarn-mappings = "1.21.10+build.2"
fabric-loader = "0.17.3"

# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.12-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client/)
meteor = "1.21.10-SNAPSHOT"

# Mods

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Meteor client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

# Mods

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
